import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { LienHolder } from './Lien-Holder';
import { Producer } from './Producer';

@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const lienholders = [
      { id: 0, name: 'AgriFund LLC - Nashville', city: 'Nashville', payableline: 'AgriFund LLC' },
      { id: 1, name: 'Agrifund LLC Dexter', city: 'Dexter', payableline: 'Agrifund LLC' },
      { id: 2, name: 'AgriFund LLC Fort Worth', city: 'Fort Worth', payableline: 'AgriFund LLC' },
      { id: 3, name: 'AgriFund LLC Jonesboro', city: 'Jonesboro', payableline: 'AgriFund LLC' },
      { id: 4, name: 'AgriFund LLC Pella', city: 'Pella', payableline: 'AgriFund LLC' },
      { id: 5, name: 'AgriFund LLC Rayville', city: 'Rayville', payableline: 'AgriFund LLC' },
      { id: 6, name: 'AgriFund Monroe', city: 'Monroe', payableline: 'AgriFund LLC' },
      { id: 7, name: 'Alliance Bank', city: '', payableline: 'Alliance Bank' },
      { id: 8, name: 'American Bank of Missouri', city: '', payableline: 'American Bank of Missouri' },
      { id: 9, name: 'American State Bank', city: '', payableline: 'American State Bank' },
      { id: 10, name: 'Arvest Bank', city: '', payableline: 'Arvest Bank' },
      { id: 11, name: 'Bancorpsouth Bank', city: '', payableline: 'Bancorpsouth Bank' },
      { id: 12, name: 'Bank 21', city: '', payableline: 'Bank 21' },
      { id: 13, name: 'Bank Midwest KC', city: 'Kansas City', payableline: 'Bank Midwest' },
      { id: 14, name: 'Bank Northwest', city: '', payableline: 'Bank Northwest' },
      { id: 15, name: 'Bank of Advance', city: '', payableline: 'Bank of Advance' },
      { id: 16, name: 'Bank of Monticello', city: '', payableline: 'Bank of Monticello' },
      { id: 17, name: 'Bank of Orrick', city: '', payableline: 'Bank of Orrick' },
      { id: 18, name: "Beck's Superior Hybrids", city: '', payableline: "Beck's Superior Hybrids" },
      { id: 19, name: 'Bennington State Bank', city: '', payableline: 'Bennington State Bank' },
      { id: 20, name: 'BTC Bank Albany', city: 'Albany', payableline: 'BTC Bank' },
      { id: 21, name: 'BTC Bank Bethany', city: 'Bethany', payableline: 'BTC Bank' },
      { id: 22, name: 'BTC Bank Pattonsburg', city: 'Pattonsburg', payableline: 'BTC Bank' },
      { id: 23, name: 'Citizens Bank & Trust', city: '', payableline: 'Citizens Bank & Trust' },
      { id: 24, name: 'Citizens Bank of Edina', city: '', payableline: 'Citizens Bank of Edina' },
      { id: 25, name: 'Clarke County State Bank', city: '', payableline: 'Clarke County State Bank' },
      { id: 26, name: 'Commodity Credit Corporation', city: '', payableline: 'Commodity Credit Corporation' },
      { id: 27, name: 'Commodity Credit Corporation Nodaway', city: 'Nodaway', payableline: 'Commodity Credit Corporation' },
      { id: 28, name: 'Community Bank of Missouri', city: '', payableline: 'Community Bank of Missouri' },
      { id: 29, name: 'Community State Bank of Missouri', city: '', payableline: 'Community State Bank of Missouri' },
      { id: 30, name: 'Communtiy First Bank', city: '', payableline: 'Communtiy First Bank' },
      { id: 31, name: 'Coop Assn # 130', city: '', payableline: 'Coop Assn # 130' },
      { id: 32, name: 'Co-Op Finance Association Inc', city: '', payableline: 'Co-Op Finance Association Inc' },
      { id: 33, name: 'Cooperative Credit Co', city: '', payableline: 'Cooperative Credit Co' },
      { id: 34, name: 'Corydon State Bank', city: '', payableline: 'Corydon State Bank' },
      { id: 35, name: 'Crop Production Services Laddonia', city: 'Laddonia', payableline: 'Crop Production Services' },
      { id: 36, name: 'Equity Bank', city: '', payableline: 'Equity Bank' },
      { id: 37, name: 'Exchange Bank of Missouri', city: '', payableline: 'Exchange Bank of Missouri' },
      { id: 38, name: 'Exchange Bank of NE Missouri', city: '', payableline: 'Exchange Bank of NE Missouri' },
      { id: 39, name: 'Farm Credit Midsouth', city: '', payableline: 'Farm Credit Midsouth' },
      { id: 40, name: 'Farm Credit Services Jefferson City', city: 'Jefferson City', payableline: 'Farm Credit Services Jefferson City' },
      { id: 41, name: 'Farm Credit Services of America', city: '', payableline: 'Farm Credit Services of America' },
      { id: 42, name: 'Farm Credit Southeast Missouri', city: '', payableline: 'Farm Credit Southeast Missouri' },
      { id: 43, name: 'Farm Credit Southeast Missouri', city: '', payableline: 'Farm Credit Southeast Missouri' },
      { id: 44, name: 'Farm Service Agency', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 45, name: 'Farm Service Agency', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 46, name: 'Farm Service Agency Albia', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 47, name: 'Farm Service Agency Cahokia', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 48, name: 'Farm Service Agency Carrollton', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 49, name: 'Farm Service Agency Chariton', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 50, name: 'Farm Service Agency Dexter', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 51, name: 'Farm Service Agency Emporia', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 52, name: 'Farm Service Agency Farmington', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 53, name: 'Farm Service Agency Higginsville', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 54, name: 'Farm Service Agency Kennet', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 55, name: 'Farm Service Agency Kirksville', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 56, name: 'Farm Service Agency Macon', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 57, name: 'Farm Service Agency Maryville', city: '', payableline: 'Farm Service Agency (FSA)' },
      { id: 58, name: 'Farm Service Agency Maysville', city: 'Maysville', payableline: 'Farm Service Agency (FSA)' },
      { id: 59, name: 'Farm Service Agency Mt Ayr', city: 'Mt Ayr', payableline: 'Farm Service Agency (FSA)' },
      { id: 60, name: 'Farm Service Agency Nevada', city: 'Nevada', payableline: 'Farm Service Agency (FSA)' },
      { id: 61, name: 'Farm Service Agency New Madrid', city: 'New Madrid', payableline: 'Farm Service Agency (FSA)' },
      { id: 62, name: 'Farm Service Agency Osceola', city: 'Osceola', payableline: 'Farm Service Agency (FSA)' },
      { id: 63, name: 'Farm Service Agency Paris', city: 'Paris', payableline: 'Farm Service Agency (FSA)' },
      { id: 64, name: 'Farm Service Agency Poplar Bluff', city: 'Poplar Bluff', payableline: 'Farm Service Agency (FSA)' },
      { id: 65, name: 'Farm Service Agency Sedalia', city: 'Sedalia', payableline: 'Farm Service Agency (FSA)' },
      { id: 66, name: 'Farm Service Agency Sigourney', city: 'Sigourney', payableline: 'Farm Service Agency (FSA)' },
      { id: 67, name: 'Farm Service Agency Trenton', city: 'Trenton', payableline: 'Farm Service Agency (FSA)' },
      { id: 68, name: 'Farmers Bank of Northern Missorui', city: '', payableline: 'Farmers Bank of Northern Missorui' },
      { id: 69, name: 'Farmers Coop', city: '', payableline: 'Farmers Coop' },
      { id: 70, name: 'Farmers Exchange', city: '', payableline: 'Farmers Exchange' },
      { id: 71, name: 'Farmers State Bank', city: '', payableline: 'Farmers State Bank' },
      { id: 72, name: 'Farmers State Bank of Aliceville', city: 'Aliceville', payableline: 'Farmers State Bank of Aliceville' },
      { id: 73, name: 'Farmers Trust & Savings Bank', city: '', payableline: 'Farmers Trust & Savings Bank' },
      { id: 74, name: 'FBN Finance LLC', city: '', payableline: 'FBN Finance LLC' },
      { id: 75, name: 'First Bank & Trust', city: '', payableline: 'First Bank & Trust' },
      { id: 76, name: 'First Commercial Bank', city: '', payableline: 'First Commercial Bank' },
      { id: 77, name: 'First Missouri Bank', city: '', payableline: 'First Missouri Bank' },
      { id: 78, name: 'First Missouri Bank of SEMO', city: '', payableline: 'First Missouri Bank of SEMO' },
      { id: 79, name: 'First Missouri State Bank', city: '', payableline: 'First Missouri State Bank' },
      { id: 80, name: 'First National Bank', city: '', payableline: 'First National Bank' },
      { id: 81, name: 'First State Bank', city: '', payableline: 'First State Bank' },
      { id: 82, name: 'First State Bank & Trust', city: '', payableline: 'First State Bank & Trust' },
      { id: 83, name: 'Focus Bank', city: '', payableline: 'Focus Bank' },
      { id: 84, name: 'Frontier Farm Credit', city: '', payableline: 'Frontier Farm Credit' },
      { id: 85, name: 'GFG Ag Finance LLC', city: '', payableline: 'GFG Ag Finance LLC' },
      { id: 86, name: 'GNBank', city: '', payableline: 'GNBank' },
      { id: 87, name: 'Goppert Financial Bank', city: '', payableline: 'Goppert Financial Bank' },
      { id: 88, name: 'Great Western Bank', city: '', payableline: 'Great Western Bank' },
      { id: 89, name: 'Great Western Bank - Corydon', city: 'Corydon', payableline: 'Great Western Bank' },
      { id: 90, name: 'Great Western Bank - Grant City', city: 'Grant City', payableline: 'Great Western Bank' },
      { id: 91, name: 'Great Western Bank - Leon', city: 'Leon', payableline: 'Great Western Bank' },
      { id: 92, name: 'Great Western Bank - Osceola', city: 'Osceola', payableline: 'Great Western Bank' },
      { id: 93, name: 'Great Western Bank - Princeton', city: 'Princeton', payableline: 'Great Western Bank' },
      { id: 94, name: 'Hawthorn Bank', city: '', payableline: 'Hawthorn Bank' },
      { id: 95, name: 'Home Exchange Bank', city: '', payableline: 'Home Exchange Bank' },
      { id: 96, name: 'Humilis Farms LLC', city: '', payableline: 'Humilis Farms LLC' },
      { id: 97, name: 'IM Carolem Capital LLC', city: '', payableline: 'IM Carolem Capital LLC' },
      { id: 98, name: 'IM HFF Missouri - Two LLC', city: '', payableline: 'IM HFF Missouri - Two LLC' },
      { id: 99, name: 'IM Podere Terranova LLC', city: '', payableline: 'IM Podere Terranova LLC' },
      { id: 100, name: 'Investors Community Bank', city: '', payableline: 'Investors Community Bank' },
      { id: 101, name: 'Kahoka State Bank', city: '', payableline: 'Kahoka State Bank' },
      { id: 102, name: 'Labette Bank', city: '', payableline: 'Labette Bank' },
      { id: 103, name: 'Land Equity Investors LLC', city: '', payableline: 'Land Equity Investors LLC' },
      { id: 104, name: 'Lyon County State Bank', city: '', payableline: 'Lyon County State Bank' },
      { id: 105, name: 'Macon-Atlanta State Bank', city: '', payableline: 'Macon-Atlanta State Bank' },
      { id: 106, name: 'Mercantile Bank', city: '', payableline: 'Mercantile Bank' },
      { id: 107, name: 'Mercantile Bank of Louisiana', city: '', payableline: 'Mercantile Bank of Louisiana' },
      { id: 108, name: 'MFA Incorporated', city: 'Columbia', payableline: 'MFA Incorporated' },
      { id: 109, name: 'Midstates Bank Harlan', city: '', payableline: 'Midstates Bank Harlan' },
      { id: 110, name: 'Midwest Grain & Barge Company', city: '', payableline: 'Midwest Grain & Barge Company' },
      { id: 111, name: 'Midwest Heritage Bank', city: '', payableline: 'Midwest Heritage Bank' },
      { id: 112, name: 'Monroe County Services Co', city: '', payableline: 'Monroe County Services Co' },
      { id: 113, name: 'Neco Seed Farms Inc', city: '', payableline: 'Neco Seed Farms Inc' },
      { id: 114, name: 'Nodaway Valley Bank', city: '', payableline: 'Nodaway Valley Bank' },
      { id: 115, name: 'Ottawa Cooperative Assn.', city: '', payableline: 'Ottawa Cooperative Assn.' },
      { id: 116, name: 'Piggott State Bank', city: '', payableline: 'Piggott State Bank' },
      { id: 117, name: 'Producers Credit Corporation', city: '', payableline: 'Producers Credit Corporation' },
      { id: 118, name: 'Producers Exchange', city: '', payableline: 'Producers Exchange' },
      { id: 119, name: 'Progressive Farm Credit', city: '', payableline: 'Progressive Farm Credit' },
      { id: 120, name: 'Putnam County State Bank', city: '', payableline: 'Putnam County State Bank' },
      { id: 121, name: 'Regional Missouri Bank Marceline', city: 'Marceline', payableline: 'Regional Missouri Bank Marceline' },
      { id: 122, name: 'Regions Bank', city: '', payableline: 'Regions Bank' },
      { id: 123, name: 'Shelby County FSA', city: '', payableline: 'Shelby County FSA' },
      { id: 124, name: 'Silex Banking Company', city: '', payableline: 'Silex Banking Company' },
      { id: 125, name: 'Simmons First Bank', city: '', payableline: 'Simmons First Bank' },
      { id: 126, name: 'Smith Grain & Fertilizer', city: '', payableline: 'Smith Grain & Fertilizer' },
      { id: 127, name: 'Southern Bank', city: '', payableline: 'Southern Bank' },
      { id: 128, name: 'State Bank', city: '', payableline: 'State Bank' },
      { id: 129, name: 'SUR-GRO Finance', city: '', payableline: 'SUR-GRO Finance' },
      { id: 130, name: 'Treynor State Bank', city: '', payableline: 'Treynor State Bank' },
      { id: 131, name: 'Tri-County Trust Co', city: '', payableline: 'Tri-County Trust Co' },
      { id: 132, name: 'Unico Bank', city: '', payableline: 'Unico Bank' },
      { id: 133, name: 'Union Bank & Trust', city: '', payableline: 'Union Bank & Trust' },
      { id: 134, name: 'United State Bank', city: '', payableline: 'United State Bank' },
      { id: 135, name: 'US Bank', city: '', payableline: 'US Bank' },
      { id: 136, name: 'Wilcross Seed', city: '', payableline: 'Wilcross Seed' },
      { id: 137, name: 'Wood & Huston Bank', city: '', payableline: 'Wood & Huston Bank' }
    ];
    const producers = [
      { id: 0, FirstName: 'AMAC Farms LLC', MiddleName: '', LastName: '', Suffix: '', BusinessName: 'AMAC Farms LLC', Address1: 'PO Box 51', Address2: '', City: 'Houstonia', State: 'MO', Zip: '65333', TaxID: '823144585', PatronNumber: '' }
    ];
    return { lienholders, producers };
  }

}
